Remove env tf var
ONSdigital/census-eq-monitoring pull request #2
Opened 2019-10-10 14:58 UTC by JamesGardiner

2019-10-11 12:39 UTC, MebinAbraham requested changes
Need to remove env from `tfvars.example`

Also, I think we need to remove the use of ENV all together, we have an `ENV` environment variable in the `create.sh` and `destroy.sh` which we should change to `EXISTING_PROJECT_ID`. This would also make the [concourse](https://github.com/ONSdigital/census-eq-concourse/pull/29) changes simpler. ENV was only needed when we wanted to provision project that we didn't know the ID to, but for this case, the ID is always known.

```tf
#!/usr/bin/env bash

set -ex

if [[ -z "$EXISTING_PROJECT_ID" ]]; then
  echo "Missing EXISTING_PROJECT_ID variable"
  exit 1
fi

TERRAFORM_STATE_BUCKET="${TERRAFORM_STATE_BUCKET:-census-eq-monitoring-tfstate}"

terraform init --upgrade --backend-config prefix=${EXISTING_PROJECT_ID} --backend-config bucket=${TERRAFORM_STATE_BUCKET}

# Roll out infrastructure
terraform apply -auto-approve

echo
echo "Successfully provisioned monitoring and alert policies"
```

Would be run using:
`EXISTING_PROJECT_ID=census-eq-mebin-v3-33511a76 ./create.sh`

2019-10-14 10:11 UTC, JamesGardiner commented
@MebinAbraham ENV is now removed entirely

2019-10-15 09:17 UTC, JamesGardiner commented
![](https://github.trello.services/images/mini-trello-icon.png) [GCP Stackdriver Alerts - logging metrics, monitoring and alert policies](https://trello.com/c/Amq6k0Az/3255-gcp-stackdriver-alerts-logging-metrics-monitoring-and-alert-policies)

2019-10-15 09:22 UTC, JamesGardiner commented
> Need to remove env from `tfvars.example`
> 
> Also, I think we need to remove the use of ENV all together, we have an `ENV` environment variable in the `create.sh` and `destroy.sh` which we should change to `EXISTING_PROJECT_ID`. This would also make the concourse changes simpler. ENV was only needed when we wanted to provision project that we didn't know the ID to, but for this case, the ID is always known.
> 
> ```terraform
> #!/usr/bin/env bash
> 
> set -ex
> 
> if [[ -z "$EXISTING_PROJECT_ID" ]]; then
>   echo "Missing EXISTING_PROJECT_ID variable"
>   exit 1
> fi
> 
> TERRAFORM_STATE_BUCKET="${TERRAFORM_STATE_BUCKET:-census-eq-monitoring-tfstate}"
> 
> terraform init --upgrade --backend-config prefix=${EXISTING_PROJECT_ID} --backend-config bucket=${TERRAFORM_STATE_BUCKET}
> 
> # Roll out infrastructure
> terraform apply -auto-approve
> 
> echo
> echo "Successfully provisioned monitoring and alert policies"
> ```
> 
> Would be run using:
> `EXISTING_PROJECT_ID=census-eq-mebin-v3-33511a76 ./create.sh`

Done

2019-10-15 09:36 UTC, MebinAbraham commented on README.md
> +Create with `EXISTING_PROJECT_ID=your-env ./create.sh`.
```suggestion
Create with `EXISTING_PROJECT_ID=your-project-id ./create.sh`.
```

2019-10-15 09:36 UTC, MebinAbraham commented on README.md
> +Destroy with `EXISTING_PROJECT_ID=your-env ./destroy.sh`
```suggestion
Destroy with `EXISTING_PROJECT_ID=your-project-id ./destroy.sh`
```

2019-10-15 09:59 UTC, MebinAbraham approved these changes
👍

2019-10-15 10:27 UTC, MebinAbraham commented
Needed for: https://github.com/ONSdigital/census-eq-concourse/pull/29

2019-10-15 16:02 UTC, pricem14pc approved these changes

2019-10-15 16:04 UTC, merged